site_name: Nidavellir

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - content.code.copy

nav:
  - "Home": index.md
  - "Api documentation": html/index.html

plugins:
  - search:
  - offline:
