name: build
run-name: ${{github.actor}} build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cmake --workflow --preset=x64-windows-clang-debug
      - run: cmake --workflow --preset=x64-windows-clang-release
      - run: cmake --workflow --preset=x64-windows-msvc-debug
      - run: cmake --workflow --preset=x64-windows-msvc-release
