name: build
run-name: ${{github.actor}} build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install pkg-config
      - run: cmake --workflow --preset=x64-linux-gcc-release
