name: build
run-name: ${{github.actor}} build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: sudo apt-get install ninja-build
      - run: cmake --workflow --preset=x64-linux-gcc-debug
      - run: cmake --workflow --preset=x64-linux-gcc-release
      - run: cmake --workflow --preset=x64-linux-clang-debug
      - run: cmake --workflow --preset=x64-linux-clang-release
