name: build-linux
run-name: ${{github.actor}} build
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: lukka/get-cmake@latest
      - run: cmake --workflow --preset=x64-linux-gcc-debug-sanitize
      - run: cmake --workflow --preset=x64-linux-gcc-relwithdebinfo-sanitize
      - run: cmake --workflow --preset=x64-linux-clang-debug-sanitize
      - run: cmake --workflow --preset=x64-linux-clang-relwithdebinfo-sanitize
