name: build
run-name: ${{github.actor}} build
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: lukka/get-cmake@latest
      - run: cmake --workflow --preset=x64-linux-gcc-debug-asan
      - run: cmake --workflow --preset=x64-linux-gcc-relwithdebinfo-asan
      - run: cmake --workflow --preset=x64-linux-clang-debug-asan
      - run: cmake --workflow --preset=x64-linux-clang-relwithdebinfo-asan
